### ISSUE TITLE
jsreport server fails when renaming assets

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-assets#20]
Steps to replicate:

1. Current jsreport master
2. Open studio and upload asset `logo.png` as image
3. Try to rename asset to `Logo.png`
4. Server crashes

```
2017-03-07T19:44:13.802Z - error: Error when processing OData PATCH: /odata/assets(I7mdaSATLuCye1Yh) Error: EPERM: operation not permitted, open 'E:\work\jsreport\jsreport\data\assets\Logo.p
ng\content.png'
    at Error (native)
```

**Comment by bjrmatos** [comment]
so far i was not able to replicate the issue, am i doing anything wrong?

![assets-issue](https://cloud.githubusercontent.com/assets/4262050/23683573/b436ea4a-0367-11e7-9505-d15df23780eb.gif)

**Comment by bjrmatos** [comment]
ok, i can reproduce the issue (for some reason the jsreport installation that i'm using was in `memory` connection).

turns out that the issue was present when renaming **any entity** (not just `assets`) when using `fs-store`
